/*  ------------------------------------------------------
     Routine name:  generate_money_automate_model
     Description:   
     Project file:  generate_exchange_money_automate.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&state_vars->generate_money_automate_modelv0_out_0_,&generate_money_automate_modelv0_out_0_default,sizeof(generate_money_automate_modelv0_out_0_default));
memcpy(&state_vars->generate_money_automate_modelv1_out_0_,&generate_money_automate_modelv1_out_0_default,sizeof(generate_money_automate_modelv1_out_0_default));
generate_money_automate_modelv1_sinit__0:
;
